/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Part3IndexRouteImport } from './routes/part-3/index'
import { Route as Part2IndexRouteImport } from './routes/part-2/index'
import { Route as Part1IndexRouteImport } from './routes/part-1/index'
import { Route as Part3OverviewRouteImport } from './routes/part-3/overview'
import { Route as Part2PurposeSelfAssessmentRouteImport } from './routes/part-2/purpose-self-assessment'
import { Route as Part2PurposeRouteImport } from './routes/part-2/purpose'
import { Route as Part2PracticesSelfAssessmentRouteImport } from './routes/part-2/practices-self-assessment'
import { Route as Part2PracticesOrganisationRouteImport } from './routes/part-2/practices-organisation'
import { Route as Part2PracticesD3RouteImport } from './routes/part-2/practices-d3'
import { Route as Part2PracticesD2RouteImport } from './routes/part-2/practices-d2'
import { Route as Part2PracticesD1RouteImport } from './routes/part-2/practices-d1'
import { Route as Part2PlanningSelfAssessmentRouteImport } from './routes/part-2/planning-self-assessment'
import { Route as Part2PlanningRouteImport } from './routes/part-2/planning'
import { Route as Part1SchoolContextRouteImport } from './routes/part-1/school-context'
import { Route as Part1LeadershipInsightsRouteImport } from './routes/part-1/leadership-insights'
import { Route as Part1CommunityVoicesRouteImport } from './routes/part-1/community-voices'
import { Route as Part1CommunityDataRouteImport } from './routes/part-1/community-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Part3IndexRoute = Part3IndexRouteImport.update({
  id: '/part-3/',
  path: '/part-3/',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2IndexRoute = Part2IndexRouteImport.update({
  id: '/part-2/',
  path: '/part-2/',
  getParentRoute: () => rootRouteImport,
} as any)
const Part1IndexRoute = Part1IndexRouteImport.update({
  id: '/part-1/',
  path: '/part-1/',
  getParentRoute: () => rootRouteImport,
} as any)
const Part3OverviewRoute = Part3OverviewRouteImport.update({
  id: '/part-3/overview',
  path: '/part-3/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2PurposeSelfAssessmentRoute =
  Part2PurposeSelfAssessmentRouteImport.update({
    id: '/part-2/purpose-self-assessment',
    path: '/part-2/purpose-self-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const Part2PurposeRoute = Part2PurposeRouteImport.update({
  id: '/part-2/purpose',
  path: '/part-2/purpose',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2PracticesSelfAssessmentRoute =
  Part2PracticesSelfAssessmentRouteImport.update({
    id: '/part-2/practices-self-assessment',
    path: '/part-2/practices-self-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const Part2PracticesOrganisationRoute =
  Part2PracticesOrganisationRouteImport.update({
    id: '/part-2/practices-organisation',
    path: '/part-2/practices-organisation',
    getParentRoute: () => rootRouteImport,
  } as any)
const Part2PracticesD3Route = Part2PracticesD3RouteImport.update({
  id: '/part-2/practices-d3',
  path: '/part-2/practices-d3',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2PracticesD2Route = Part2PracticesD2RouteImport.update({
  id: '/part-2/practices-d2',
  path: '/part-2/practices-d2',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2PracticesD1Route = Part2PracticesD1RouteImport.update({
  id: '/part-2/practices-d1',
  path: '/part-2/practices-d1',
  getParentRoute: () => rootRouteImport,
} as any)
const Part2PlanningSelfAssessmentRoute =
  Part2PlanningSelfAssessmentRouteImport.update({
    id: '/part-2/planning-self-assessment',
    path: '/part-2/planning-self-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const Part2PlanningRoute = Part2PlanningRouteImport.update({
  id: '/part-2/planning',
  path: '/part-2/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const Part1SchoolContextRoute = Part1SchoolContextRouteImport.update({
  id: '/part-1/school-context',
  path: '/part-1/school-context',
  getParentRoute: () => rootRouteImport,
} as any)
const Part1LeadershipInsightsRoute = Part1LeadershipInsightsRouteImport.update({
  id: '/part-1/leadership-insights',
  path: '/part-1/leadership-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const Part1CommunityVoicesRoute = Part1CommunityVoicesRouteImport.update({
  id: '/part-1/community-voices',
  path: '/part-1/community-voices',
  getParentRoute: () => rootRouteImport,
} as any)
const Part1CommunityDataRoute = Part1CommunityDataRouteImport.update({
  id: '/part-1/community-data',
  path: '/part-1/community-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/part-1/community-data': typeof Part1CommunityDataRoute
  '/part-1/community-voices': typeof Part1CommunityVoicesRoute
  '/part-1/leadership-insights': typeof Part1LeadershipInsightsRoute
  '/part-1/school-context': typeof Part1SchoolContextRoute
  '/part-2/planning': typeof Part2PlanningRoute
  '/part-2/planning-self-assessment': typeof Part2PlanningSelfAssessmentRoute
  '/part-2/practices-d1': typeof Part2PracticesD1Route
  '/part-2/practices-d2': typeof Part2PracticesD2Route
  '/part-2/practices-d3': typeof Part2PracticesD3Route
  '/part-2/practices-organisation': typeof Part2PracticesOrganisationRoute
  '/part-2/practices-self-assessment': typeof Part2PracticesSelfAssessmentRoute
  '/part-2/purpose': typeof Part2PurposeRoute
  '/part-2/purpose-self-assessment': typeof Part2PurposeSelfAssessmentRoute
  '/part-3/overview': typeof Part3OverviewRoute
  '/part-1/': typeof Part1IndexRoute
  '/part-2/': typeof Part2IndexRoute
  '/part-3/': typeof Part3IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/part-1/community-data': typeof Part1CommunityDataRoute
  '/part-1/community-voices': typeof Part1CommunityVoicesRoute
  '/part-1/leadership-insights': typeof Part1LeadershipInsightsRoute
  '/part-1/school-context': typeof Part1SchoolContextRoute
  '/part-2/planning': typeof Part2PlanningRoute
  '/part-2/planning-self-assessment': typeof Part2PlanningSelfAssessmentRoute
  '/part-2/practices-d1': typeof Part2PracticesD1Route
  '/part-2/practices-d2': typeof Part2PracticesD2Route
  '/part-2/practices-d3': typeof Part2PracticesD3Route
  '/part-2/practices-organisation': typeof Part2PracticesOrganisationRoute
  '/part-2/practices-self-assessment': typeof Part2PracticesSelfAssessmentRoute
  '/part-2/purpose': typeof Part2PurposeRoute
  '/part-2/purpose-self-assessment': typeof Part2PurposeSelfAssessmentRoute
  '/part-3/overview': typeof Part3OverviewRoute
  '/part-1': typeof Part1IndexRoute
  '/part-2': typeof Part2IndexRoute
  '/part-3': typeof Part3IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/part-1/community-data': typeof Part1CommunityDataRoute
  '/part-1/community-voices': typeof Part1CommunityVoicesRoute
  '/part-1/leadership-insights': typeof Part1LeadershipInsightsRoute
  '/part-1/school-context': typeof Part1SchoolContextRoute
  '/part-2/planning': typeof Part2PlanningRoute
  '/part-2/planning-self-assessment': typeof Part2PlanningSelfAssessmentRoute
  '/part-2/practices-d1': typeof Part2PracticesD1Route
  '/part-2/practices-d2': typeof Part2PracticesD2Route
  '/part-2/practices-d3': typeof Part2PracticesD3Route
  '/part-2/practices-organisation': typeof Part2PracticesOrganisationRoute
  '/part-2/practices-self-assessment': typeof Part2PracticesSelfAssessmentRoute
  '/part-2/purpose': typeof Part2PurposeRoute
  '/part-2/purpose-self-assessment': typeof Part2PurposeSelfAssessmentRoute
  '/part-3/overview': typeof Part3OverviewRoute
  '/part-1/': typeof Part1IndexRoute
  '/part-2/': typeof Part2IndexRoute
  '/part-3/': typeof Part3IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/part-1/community-data'
    | '/part-1/community-voices'
    | '/part-1/leadership-insights'
    | '/part-1/school-context'
    | '/part-2/planning'
    | '/part-2/planning-self-assessment'
    | '/part-2/practices-d1'
    | '/part-2/practices-d2'
    | '/part-2/practices-d3'
    | '/part-2/practices-organisation'
    | '/part-2/practices-self-assessment'
    | '/part-2/purpose'
    | '/part-2/purpose-self-assessment'
    | '/part-3/overview'
    | '/part-1/'
    | '/part-2/'
    | '/part-3/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/part-1/community-data'
    | '/part-1/community-voices'
    | '/part-1/leadership-insights'
    | '/part-1/school-context'
    | '/part-2/planning'
    | '/part-2/planning-self-assessment'
    | '/part-2/practices-d1'
    | '/part-2/practices-d2'
    | '/part-2/practices-d3'
    | '/part-2/practices-organisation'
    | '/part-2/practices-self-assessment'
    | '/part-2/purpose'
    | '/part-2/purpose-self-assessment'
    | '/part-3/overview'
    | '/part-1'
    | '/part-2'
    | '/part-3'
  id:
    | '__root__'
    | '/'
    | '/part-1/community-data'
    | '/part-1/community-voices'
    | '/part-1/leadership-insights'
    | '/part-1/school-context'
    | '/part-2/planning'
    | '/part-2/planning-self-assessment'
    | '/part-2/practices-d1'
    | '/part-2/practices-d2'
    | '/part-2/practices-d3'
    | '/part-2/practices-organisation'
    | '/part-2/practices-self-assessment'
    | '/part-2/purpose'
    | '/part-2/purpose-self-assessment'
    | '/part-3/overview'
    | '/part-1/'
    | '/part-2/'
    | '/part-3/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Part1CommunityDataRoute: typeof Part1CommunityDataRoute
  Part1CommunityVoicesRoute: typeof Part1CommunityVoicesRoute
  Part1LeadershipInsightsRoute: typeof Part1LeadershipInsightsRoute
  Part1SchoolContextRoute: typeof Part1SchoolContextRoute
  Part2PlanningRoute: typeof Part2PlanningRoute
  Part2PlanningSelfAssessmentRoute: typeof Part2PlanningSelfAssessmentRoute
  Part2PracticesD1Route: typeof Part2PracticesD1Route
  Part2PracticesD2Route: typeof Part2PracticesD2Route
  Part2PracticesD3Route: typeof Part2PracticesD3Route
  Part2PracticesOrganisationRoute: typeof Part2PracticesOrganisationRoute
  Part2PracticesSelfAssessmentRoute: typeof Part2PracticesSelfAssessmentRoute
  Part2PurposeRoute: typeof Part2PurposeRoute
  Part2PurposeSelfAssessmentRoute: typeof Part2PurposeSelfAssessmentRoute
  Part3OverviewRoute: typeof Part3OverviewRoute
  Part1IndexRoute: typeof Part1IndexRoute
  Part2IndexRoute: typeof Part2IndexRoute
  Part3IndexRoute: typeof Part3IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-3/': {
      id: '/part-3/'
      path: '/part-3'
      fullPath: '/part-3/'
      preLoaderRoute: typeof Part3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/': {
      id: '/part-2/'
      path: '/part-2'
      fullPath: '/part-2/'
      preLoaderRoute: typeof Part2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-1/': {
      id: '/part-1/'
      path: '/part-1'
      fullPath: '/part-1/'
      preLoaderRoute: typeof Part1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-3/overview': {
      id: '/part-3/overview'
      path: '/part-3/overview'
      fullPath: '/part-3/overview'
      preLoaderRoute: typeof Part3OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/purpose-self-assessment': {
      id: '/part-2/purpose-self-assessment'
      path: '/part-2/purpose-self-assessment'
      fullPath: '/part-2/purpose-self-assessment'
      preLoaderRoute: typeof Part2PurposeSelfAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/purpose': {
      id: '/part-2/purpose'
      path: '/part-2/purpose'
      fullPath: '/part-2/purpose'
      preLoaderRoute: typeof Part2PurposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/practices-self-assessment': {
      id: '/part-2/practices-self-assessment'
      path: '/part-2/practices-self-assessment'
      fullPath: '/part-2/practices-self-assessment'
      preLoaderRoute: typeof Part2PracticesSelfAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/practices-organisation': {
      id: '/part-2/practices-organisation'
      path: '/part-2/practices-organisation'
      fullPath: '/part-2/practices-organisation'
      preLoaderRoute: typeof Part2PracticesOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/practices-d3': {
      id: '/part-2/practices-d3'
      path: '/part-2/practices-d3'
      fullPath: '/part-2/practices-d3'
      preLoaderRoute: typeof Part2PracticesD3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/practices-d2': {
      id: '/part-2/practices-d2'
      path: '/part-2/practices-d2'
      fullPath: '/part-2/practices-d2'
      preLoaderRoute: typeof Part2PracticesD2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/practices-d1': {
      id: '/part-2/practices-d1'
      path: '/part-2/practices-d1'
      fullPath: '/part-2/practices-d1'
      preLoaderRoute: typeof Part2PracticesD1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/planning-self-assessment': {
      id: '/part-2/planning-self-assessment'
      path: '/part-2/planning-self-assessment'
      fullPath: '/part-2/planning-self-assessment'
      preLoaderRoute: typeof Part2PlanningSelfAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-2/planning': {
      id: '/part-2/planning'
      path: '/part-2/planning'
      fullPath: '/part-2/planning'
      preLoaderRoute: typeof Part2PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-1/school-context': {
      id: '/part-1/school-context'
      path: '/part-1/school-context'
      fullPath: '/part-1/school-context'
      preLoaderRoute: typeof Part1SchoolContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-1/leadership-insights': {
      id: '/part-1/leadership-insights'
      path: '/part-1/leadership-insights'
      fullPath: '/part-1/leadership-insights'
      preLoaderRoute: typeof Part1LeadershipInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-1/community-voices': {
      id: '/part-1/community-voices'
      path: '/part-1/community-voices'
      fullPath: '/part-1/community-voices'
      preLoaderRoute: typeof Part1CommunityVoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/part-1/community-data': {
      id: '/part-1/community-data'
      path: '/part-1/community-data'
      fullPath: '/part-1/community-data'
      preLoaderRoute: typeof Part1CommunityDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Part1CommunityDataRoute: Part1CommunityDataRoute,
  Part1CommunityVoicesRoute: Part1CommunityVoicesRoute,
  Part1LeadershipInsightsRoute: Part1LeadershipInsightsRoute,
  Part1SchoolContextRoute: Part1SchoolContextRoute,
  Part2PlanningRoute: Part2PlanningRoute,
  Part2PlanningSelfAssessmentRoute: Part2PlanningSelfAssessmentRoute,
  Part2PracticesD1Route: Part2PracticesD1Route,
  Part2PracticesD2Route: Part2PracticesD2Route,
  Part2PracticesD3Route: Part2PracticesD3Route,
  Part2PracticesOrganisationRoute: Part2PracticesOrganisationRoute,
  Part2PracticesSelfAssessmentRoute: Part2PracticesSelfAssessmentRoute,
  Part2PurposeRoute: Part2PurposeRoute,
  Part2PurposeSelfAssessmentRoute: Part2PurposeSelfAssessmentRoute,
  Part3OverviewRoute: Part3OverviewRoute,
  Part1IndexRoute: Part1IndexRoute,
  Part2IndexRoute: Part2IndexRoute,
  Part3IndexRoute: Part3IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
